#---------------------------------------------------------------------------
# functions to debug mdi-manager code changes
#---------------------------------------------------------------------------
# developers should create file 'gitCredentials.R' in MDI_DIR or HOME as follows:
#   Sys.setenv(GIT_USER = 'xxx')
#   Sys.setenv(GITHUB_PAT = 'xxx')
#---------------------------------------------------------------------------
debugInstall <- function(
    mdiDir = 'C:/mdi',
    debugDir = NA, # 'test-installation', # path relative to mdiDir where mdi will be installed
    force = FALSE, # if TRUE, completely remove prior installation before installing
    clone = FALSE
){
    # initialize
    initializeDebug(mdiDir, debugDir)

    # remove the last installation (but only if a specific installation subdirectory was defined)
    if(!is.na(debugDir)){
        if(force){
            message()
            message('REMOVING MDI INSTALLATION')
            unlink(debugDir, recursive = TRUE, force = TRUE)
        }
        if(!dir.exists(debugDir)) dir.create(debugDir)
    }

    # run the installation
    message()
    message('INSTALLING THE MDI')
    message()
    mdi::install(
        mdiDir = if(is.na(debugDir)) mdiDir else debugDir, 
        confirm = FALSE,
        clone = clone
    )
}
debugRun <- function(
    mdiDir = 'C:/mdi',
    debugDir = NA, # 'test-installation', # path relative to mdiDir
    install = TRUE,
    developer = TRUE
){
    # initialize
    initializeDebug(mdiDir, debugDir)

    # run the MDI
    message()
    message('RUNNING THE MDI')
    message()
    mdi::run(
        mdiDir = if(is.na(debugDir)) mdiDir else debugDir, 
        install = install,
        developer = developer
    )
}
initializeDebug <- function(mdiDir, debugDir){

    # set working directory
    setwd(mdiDir)
    message(paste("working directory:", mdiDir))
    message(paste("installation subdirectory:", debugDir))

    # detach prior mdi package
    message()
    message('DETACHING MDI')
    unloadNamespace("mdi")

    # rebuild the manager package
    message()
    message('UPDATING MDI MANAGER PACKAGE')
    managerDir <- 'manager/developer-forks/mdi-manager'
    remotes::install_local(
        path = managerDir,
        force = TRUE
    )
    devtools::document(managerDir)
    docsToMarkdown(managerDir)
}

# convert R documentation files to markdown for Jekyll GitHub Pages
docsToMarkdown <- function(managerDir){
    i <- 1
    # enumerate function targets manually (forces the order, and may not want all in documentation site)
    for(action in c("install", "run", "password_store")){
        rdfile <- paste(file.path(managerDir, "man", action), 'Rd', sep = ".")
        mdFile <- paste(file.path(managerDir, "docs", "actions", action), 'md', sep = ".")
        message( paste("converting", rdfile, "to", mdFile) )
        frontMatter <- paste(
            "---",
            paste("title:", action),
            paste("parent:", "R_Commands"),
            paste("has_children:", "false"),
            paste("nav_order:", i),
            "---",
            "",
            "<!-- FILE GENERATED BY document.R - DO NOT EDIT MANUALLY -->",
            "",
            sep = "\n"
        )
        cat(frontMatter, file = mdFile, sep = "\n", append = FALSE)
        Rd2md::Rd2markdown(rdfile, mdFile, append = TRUE)
        i <- i + 1
    }    
}
