# convert R documentation files to markdown for Jekyll GitHub Pages
i <- 1
for(action in c("install", "run")){
    rdfile <- paste(file.path("man", action), 'Rd', sep = ".")
    mdFile <- paste(file.path("docs", "actions", action), 'md', sep = ".")
    message( paste("converting", rdfile, "to", mdFile) )
    frontMatter <- paste(
        "---",
        paste("title:", action),
        paste("parent:", "R_Commands"),
        paste("has_children:", "false"),
        paste("nav_order:", i),
        "---",
        "",
        "<!-- FILE GENERATED BY document.R - DO NOT EDIT MANUALLY -->",
        "",
        sep = "\n"
    )
    cat(frontMatter, file = mdFile, sep = "\n", append = FALSE)
    Rd2md::Rd2markdown(rdfile, mdFile, append = TRUE)
    i <- i + 1
}
