---
#----------------------------------------------------------------------
# Configuration data for a Michigan Data Interface installation.
#----------------------------------------------------------------------

#----------------------------------------------------------------------
# STAGE 1 PIPELINES AND STAGE 2 APPS SUITES TO INSTALL
#----------------------------------------------------------------------
# Entries must be arrays of valid GitHub repositories that can  be cloned 
# by 'mdi::install()'. Developers should _not_ list their repo forks here,
# they will be cloned automatically if a 'gitUser' is provided to 
# 'mdi::install()'. Only pipelines or apps suites listed here during the 
# most recent call to 'mdi::install()' will be available to 'mdi' or 
# 'mdi::run()', respectively. When a target name conflicts between multiple 
# suites, the first one encountered in the order below will be used.
#----------------------------------------------------------------------
suites:
    # Stage 1: HPC analysis pipeline suites
    pipelines:
        # - https://github.com/GIT_USER/SUITE_NAME-mdi-pipelines.git

    # Stage 2: interactive web app suites
    apps:
        # - https://github.com/GIT_USER/SUITE_NAME-mdi-apps.git

#--------------------------------------------------------------
# STAGE 1 PIPELINE ENVIRONMENT VARIABLES AND OPTION DEFAULTS
#--------------------------------------------------------------
#   - typically constant for all Stage 1 jobs run on a given server
#   - can be overridden in lower level config files
#   - variables are available for use in <data.yml> by end user
#   - options are available as variables in the environment of running jobs
#   - default values are appropriate for UM Great Lakes
#   - by convention variable names are ALL_UPPER_CASE
#--------------------------------------------------------------
variables:
    # conda module (for creating runtime environments)
    ANACONDA: python3.8-anaconda/2020.07

    # sequence resources
    GENOMES_DIR: $HOME/resources/genomes

# defaults for options in data.yml templates
shared:
    resources:
        tmp-dir: /tmpssd  
    genome:
        genomes-dir: $GENOMES_DIR

# configure a shared conda implementation
conda:
    # where MDI program environments are installed
    base-directory: $HOME/mdi/environments
    
    # optional command to load conda for use (e.g. 'module load conda')
    load-command: module load $ANACONDA
    
    # path to conda.sh initialization script
    # if null, tries $(conda info --base)/etc/profile.d/conda.sh
    profile-script: /sw/arcts/centos7/$ANACONDA/etc/profile.d/conda.sh

#----------------------------------------------------------------------
# GLOBUS CLIENT APPLICATION AND CONNECT ENDPOINT
#----------------------------------------------------------------------
# Globus is only required if your web server needs to:
#    transfer files for data analysis (instead of uploading them into the web page)
#    upload job definitions to run pipelines on a cluster server
#    run on a public web server, where authentication is required
# Leave values as null if you will not use Globus.
#----------------------------------------------------------------------
# This section contains:
#   1) the Globus client application key and secret
#   2) the UUID of a Globus Connect endpoint for your computer
#   3) the UUID of a MDI Users group (advanced users only!)
#----------------------------------------------------------------------
# Learn about setting up your Globus client application here:
#       https://docs.globus.org/api/auth/
# and create your client application here:
#       https://developers.globus.org/
# Note: 'key' is synonymous with 'client ID'
#----------------------------------------------------------------------
# Learn about setting up a Globus Connect Personal endpoint here:
#       https://www.globus.org/globus-connect-personal
# and create it here:
#       https://app.globus.org/endpoints
# then get the endpoint UUID here:
#       https://app.globus.org/endpoints?scope=administered-by-me
#----------------------------------------------------------------------
globus: 

    # the client application (app) you created in your Globus account
    client:
        key:    null
        secret: null

    # a random string to sign keys; required if you specify a client application
    # try: https://www.grc.com/passwords.htm
    signature:  null

    # the Globus Connect endpoint you created in your Globus account for your computer
    endpoint:
        id:        null
        localPath: null

    # the UUID of the MDI Users group (most people should leave this as null)
    usersGroup: null
