---
# optional command to load singularity
# leave as null if singularity is already in PATH or can be loaded with `module load singularity`
# quotes, if present, are included as part of the command
load-command: null
