---
#--------------------------------------------------------------
# Stage 1 Pipeline global variables and default options
#--------------------------------------------------------------
#   - typically constant for all Stage 1 jobs on a given server
#   - can be overridden in lower level config files
#   - variables are available for use in <data.yml> by an end user
#   - options are available as variables in the environment of running jobs
#   - initial values for an installation are appropriate for UM Great Lakes
#   - by convention variable names are ALL_UPPER_CASE
#--------------------------------------------------------------
variables:
  # conda module (for creating runtime environments)
  ANACONDA: python3.8-anaconda/2020.07

# defaults for options in data.yml templates
shared:
  resources:
    tmp-dir: /tmpssd  
    tmp-dir-large: /tmp

# configure a shared conda implementation
conda:
    
  # optional command to load conda for use (e.g. 'module load conda')
  # use null if conda is always available on the server where mdi is run
  load-command: module load $ANACONDA
    
  # path to conda.sh initialization script
  # if null, tries $(conda info --base)/etc/profile.d/conda.sh
  profile-script: /sw/arcts/centos7/$ANACONDA/etc/profile.d/conda.sh

# optional command to load singularity if not already available in PATH
singularity:
  load-command: module load singularity # cannot include variables
