---
#----------------------------------------------------------------------
# MDI tool suites to install
#----------------------------------------------------------------------
#   - entries should point to GitHub repositories
#   - developers should _not_ list their repo forks here
#   - when a pipeline/app name is in multiple suites, the first match is used
#----------------------------------------------------------------------
# !! Re-run 'mdi::install()' or 'mdi install' after updating this list !!
#----------------------------------------------------------------------
suites:
  # - https://github.com/GIT_USER/SUITE_NAME-mdi-tools.git
  # - GIT_USER/SUITE_NAME-mdi-tools # either format works
