#---------------------------------------------------------------------------
#' Generate a salted and hashed access key suitable for storing on disk
#' 
#' Hash values generated by \code{mdi::password_store()} are the strings that
#' should be pasted into config file 'stage2-apps.yml'.
#'
#' Please note that access_control 'keys' offer only modest security.
#' Their main utility is to prevent people from using your server more than
#' to enforce strict data protection. You should protect your server through 
#' additional means such as an IP firewall and ensure that your MDI installation 
#' files are secure.
#' 
#' @param key character. The access key that will by typed into the web
#' interface by a user to gain access to your MDI apps server.
#'  
#' @return A hash value ready for pasting into config file 'stage2-apps.yml'.
#'
#' @export
#---------------------------------------------------------------------------
password_store <- function(key){
    salt <- paste0(sample(c(letters, 0:9), 32), collapse = "")
    saltedKey <- paste0(salt, key)
    hash <- digest::digest(saltedKey)
    hashWithSalt <- paste(salt, hash, sep = "_")
    hashWithSalt
}
